name: where
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Dio Package
  dio: ^4.0.0
  get: ^4.2.5
  cached_network_image: ^3.1.0
  table_calendar: ^3.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.6
  animated_splash_screen: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  http: any
  json_annotation: any
  flutter_dropdown: ^0.0.8
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker: ^0.8.2
  persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.0.6
  font_awesome_flutter: ^9.1.0
  shimmer: ^2.0.0
  connectivity: ^3.0.6
  flutter_easyloading: ^3.0.0
  expandable: ^5.0.1
  rflutter_alert: ^2.0.2


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/splash_background.png
    - images/login_background.png
    - images/splash_logo.png
    - images/introduction.png
    - images/where_logo.png
    - images/m1.jpg
    - images/m2.jpg
    - images/w1.jpg
    - images/w2.jpg
    - images/testing_barcode.png
    - images/tier_loyalty_card.png
    - images/member_name_loyalty_card.png
    - images/points_loyalty_card.png
    - images/logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family:  Following
      fonts:
        - asset: fonts/Following.ttf
    - family:  Follower
      fonts:
        - asset: fonts/Follower.ttf
    - family:  BottomNavIcon
      fonts:
        - asset: fonts/BottomNavIcon.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
